# Site
name: "Salesforce Lwc"
title: "Salesforce Lwc"
description: "Salesforce LWC is a platform where you can learn Salesforce, Aura components, Lightning web components and Apex with relevant scenarios. Salesforce CRM Software is one of the most preferred CRM in the CRM Industry."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-139422731-1'
disqus: 'salesforcelwc'
mailchimp-list: 'https://salesforcelwc.us20.list-manage.com/subscribe/post?u=310725db7e557758a03138e92&amp;id=108e4f0200'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  kishore:
    name: Kishore
    display_name: Kishore
    gravatar: 07fb9d10b9b6d171fa6edc6078956b4b
    email: salesforcelwc@gmail.com
    web: https://www.salesforcelwc.in
    twitter: https://twitter.com/KishoreSfdc
    description: "I am a Salesforce developer and a so-called blogger at SalesforceLwc. I love learning and sharing. SalesforceLWC aims to share relevant knowledge and scenarios for understanding Salesforce Lightning Web Components and AURA. I have also started learning the Python programming language."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-6753262254014660"
adsense-data-ad-slot: "8811166651"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
