# Site
name: "Salesforce Lwc"
title: "Salesforce Lwc"
description: "SalesforceLWC is a platform where you can learn Salesforce, Aura components, Lightning web components and Apex with relevant scenarios and easily understandable examples. All about Salesforce CRM Software."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-46278016-1'
disqus: 'salesforcelwc'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  kishore:
    name: Kishore
    display_name: Kishore
    gravatar: 07fb9d10b9b6d171fa6edc6078956b4b
    email: salesforcelwc@gmail.com
    web: https://www.salesforcelwc.in
    twitter: https://twitter.com/KishoreSfdc
    description: "I am a Salesforce developer and a so-called blogger at SalesforceLwc. I love learning and sharing. SalesforceLWC aims to share relevant knowledge and scenarios for understanding Salesforce Lightning Web Components and AURA. I have also started learning the Python programming language."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
